---
type: showroom

# Set the left column width to 30%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

tabs:
  # OCP Console
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'

  - name: Terminal 1
    path: /terminal/
    port: 443
    secondary_name: Terminal 2
    secondary_path: /terminal/
    secondary_port: 443

  # # External page
  # - name: Llamastack Docs
  #   url: 'https://llama-stack.readthedocs.io/en/latest/'
